# Generated by Django 5.1.1 on 2024-09-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service_delete_moodentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('feelings', models.TextField()),
                ('mood_intensity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('service', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('category', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('additional_experience', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
