# Generated by Django 5.1.1 on 2024-10-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_id_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_experience',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
